# Generated by Django 4.1.3 on 2022-11-14 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbroad', '0002_rubic_alter_bb_options_alter_bb_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rubic',
            new_name='Rubric',
        ),
        migrations.AddField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bbroad.rubric', verbose_name='Рубрика'),
        ),
    ]
